=== sihammchita/TP_Gestion-des-donn-es-du-Web/aeroport.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT Aeroport (Employes, Pistes, Compagnies, Avions, Vols)>

<!ELEMENT Employes (Employe+)>
<!ELEMENT Employe (NomEmploye, Prenom, Age, Poste)>
<!ELEMENT NomEmploye (#PCDATA)>
<!ELEMENT Prenom (#PCDATA)>
<!ELEMENT Age (#PCDATA)>
<!ELEMENT Poste (#PCDATA)>

<!ELEMENT Pistes (Piste+)>
<!ELEMENT Piste (NomPiste, Longueur, Etat)>
<!ELEMENT NomPiste (#PCDATA)>
<!ELEMENT Longueur (#PCDATA)>
<!ELEMENT Etat (#PCDATA)>

<!ELEMENT Compagnies (Compagnie+)>
<!ELEMENT Compagnie (NomCompagnie, Pays)>
<!ELEMENT NomCompagnie (#PCDATA)>
<!ELEMENT Pays (#PCDATA)>

<!ELEMENT Avions (Avion+)>
<!ELEMENT Avion (Modele, CompagnieRef, Capacite)>
<!ELEMENT Modele (#PCDATA)>
<!ELEMENT CompagnieRef (#PCDATA)>
<!ELEMENT Capacite (#PCDATA)>

<!ELEMENT Vols (Vol+)>
<!ELEMENT Vol (Numero, AvionRef, Depart, Arrivee, Heure, Destination, Date, Piste_vol, PiloteId)>
<!ELEMENT Numero (#PCDATA)>
<!ELEMENT AvionRef (#PCDATA)>
<!ELEMENT Depart (#PCDATA)>
<!ELEMENT Arrivee (#PCDATA)>
<!ELEMENT Heure (#PCDATA)>
<!ELEMENT Destination (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Piste_vol (#PCDATA)> 
<!ELEMENT PiloteId (#PCDATA)>

=== sihammchita/TP_Gestion-des-donn-es-du-Web/Aeroport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Aeroport SYSTEM "aeroport.dtd">
<Aeroport>
    <Employes>
        <Employe>
            <NomEmploye>Dupont</NomEmploye>
            <Prenom>Jean</Prenom>
            <Age>34</Age>
            <Poste>Technicien</Poste>
            
        </Employe>
    </Employes>    
    <Pistes>
        <Piste>
            <NomPiste>Nord</NomPiste>
            <Longueur>3500</Longueur>
            <Etat>Disponible</Etat>
        </Piste>
    </Pistes>
    
    <Compagnies>
        <Compagnie>
            <NomCompagnie>Air France</NomCompagnie>
            <Pays>France</Pays>
        </Compagnie>
    </Compagnies>
    
    <Avions>
        <Avion>
            <Modele>Airbus A320</Modele>
            <CompagnieRef>Air France</CompagnieRef> 
            <Capacite>180</Capacite>
        </Avion>
    </Avions>
    
    <Vols>
        <Vol>
            <Numero>AF1234</Numero>
            <AvionRef>Airbus A320</AvionRef>
            <Depart>Piste Nord</Depart>
            <Arrivee>Piste Sud</Arrivee>
            <Heure>08:30</Heure>
            <Destination>Paris</Destination>
            <Date>2024-11-15T08:30:00Z</Date> 
            <Piste_vol>Piste Nord</Piste_vol>
            <PiloteId>123</PiloteId>
            

        </Vol>
    </Vols>
</Aeroport>
